trigger:
- none

pool:
  vmImage: 'windows-latest'

parameters:
- name: resourcegroup
  displayName: 'Resource Group Name'
  type: string
- name: environment
  displayName: 'Environment'
  type: string
  values:
  - 'Non-Prod'
  - 'Prod'
- name: FullProcess
  displayName: 'Trigger the whole Procesos'
  type: boolean
  default: false
- name: KeyVault
  displayName: 'Key Vault Info'
  type: boolean
  default: false
- name: AppServicePlan
  displayName: 'App Service Plan Info'
  type: boolean
  default: false
- name: FunctionApp
  displayName: 'Function App Info'
  type: boolean
  default: false
- name: WebSite
  displayName: 'Web Site Info'
  type: boolean
  default: false
- name: StorageAccount
  displayName: 'Storage Account Info'
  type: boolean
  default: false
- name: VirtualMachine
  displayName: 'Virtual Machine Info'
  type: boolean
  default: false

variables:
  - group: ${{parameters.environment}}

stages:
- stage : Key_Vault_Info
  displayName: Get KV Info
    jobs:
      - template: Templates/keyvault.yaml
        parameters:
          azureSubscription: $(azureSubscription)
          resourcegroup: ${{parameters.resourcegroup}}
          storageAccountName: $(storageAccountName)
          storageAccountAccessKey: $(storageAccountAccessKey)
          storageContainerName: $(storageContainerName)
          FullProcess: ${{parameters.FullProcess}}
          KeyVault: ${{parameters.KeyVault}}

- stage: App_Service_Plan_Info
  displayName: Get SP Info
    jobs:
      - template: Templates/appserviceplan.yaml
        parameters:
          azureSubscription: $(azureSubscription)
          resourcegroup: ${{parameters.resourcegroup}}
          storageAccountName: $(storageAccountName)
          storageAccountAccessKey: $(storageAccountAccessKey)
          storageContainerName: $(storageContainerName)
          FullProcess: ${{parameters.FullProcess}}
          AppServicePlan: ${{parameters.AppServicePlan}}

- stage: Function_App_Info
  displayName: Get FA Info
    jobs:
      - template: Templates/functionapp.yaml
        parameters:
          azureSubscription: $(azureSubscription)
          resourcegroup: ${{parameters.resourcegroup}}
          storageAccountName: $(storageAccountName)
          storageAccountAccessKey: $(storageAccountAccessKey)
          storageContainerName: $(storageContainerName)
          FullProcess: ${{parameters.FullProcess}}
          FunctionApp: ${{parameters.FunctionApp}}

- stage: WebApp_Info
  displayName: Get WA Info
    jobs:
      - template: Templates/website.yaml
        parameters:
          azureSubscription: $(azureSubscription)
          resourcegroup: ${{parameters.resourcegroup}}
          storageAccountName: $(storageAccountName)
          storageAccountAccessKey: $(storageAccountAccessKey)
          storageContainerName: $(storageContainerName)
          FullProcess: ${{parameters.FullProcess}}
          WebSite: ${{parameters.WebSite}}

- stage: Storage_Account_Info
  displayName: Get SA Info
    jobs:
      - template: Templates/storageaccount.yaml
        parameters:
          azureSubscription: $(azureSubscription)
          resourcegroup: ${{parameters.resourcegroup}}
          storageAccountName: $(storageAccountName)
          storageAccountAccessKey: $(storageAccountAccessKey)
          storageContainerName: $(storageContainerName)
          FullProcess: ${{parameters.FullProcess}}
          StorageAccount: ${{parameters.StorageAccount}}

- stage: Virtual_Machine_Info
  displayName: Get VM Info
  dependsOn:
  - Storage_Account_Info
    jobs:
- template: Templates/virtualmachine.yaml
  parameters:
    azureSubscription: $(azureSubscription)
    resourcegroup: ${{parameters.resourcegroup}}
    storageAccountName: $(storageAccountName)
    storageAccountAccessKey: $(storageAccountAccessKey)
    storageContainerName: $(storageContainerName)
    FullProcess: ${{parameters.FullProcess}}
    VirtualMachine: ${{parameters.VirtualMachine}}