parameters:
- name: outputFileName
  default: "appServiceplan.txt"
- name: ContainerFolder
  default: "appserviceplaninfo"
- name: azureSubscription
  type: string
- name: resourcegroup
  type: string
- name: storageAccountName
  type: string
- name: storageAccountAccessKey
  type: string
- name: storageContainerName
  type: string
- name: FullProcess
  type: boolean
- name: AppServicePlan

jobs:
- job: GetAppServicePlanInfo
  condition: ${{ or(eq(parameters.FullProcess, true), eq(parameters.AppServicePlan, true)) }}
  steps:

  - template: Modules/azurepowershell.yaml

  - task: AzurePowerShell@5
    displayName: 'Get App Service Plan Info'
    inputs:
      azureSubscription: $(azureSubscription)
      ScriptPath: '$(Build.SourcesDirectory)/Templates/Scripts/key_vault_info.ps1'
      ScriptArguments: '-resourceGroup "${{parameters.resourcegroup}}" -outputFilePath "${{parameters.resourcegroup}}_${{parameters.outputFileName}}"'
      azurePowerShellVersion: LatestVersion
        
       

  - task: AzurePowerShell@5
    displayName: 'Upload File to Azure Blob Storage'
    inputs:
      azureSubscription: $(azureSubscription)
      ScriptType: 'InlineScript'
      Inline: |
        $filePath = "$(Agent.BuildDirectory)/${{parameters.resourcegroup}}_${{parameters.outputFileName}}"
        $blobName = '${{parameters.ContainerFolder}}/${{parameters.resourcegroup}}_${{parameters.outputFileName}}'

        $storageContext = New-AzStorageContext -StorageAccountName $(storageAccountName) -StorageAccountKey $(storageAccountAccessKey)
        Set-AzStorageBlobContent -Context $storageContext -Container $(storageContainerName) -File $filePath -Blob $blobName -Force

      azurePowerShellVersion: 'LatestVersion'