parameters:
- name: outputFileName
  default: "FunctionApp.txt"
- name: ContainerFolder
  default: "functionappinfo"
- name: azureSubscription
  type: string
- name: resourcegroup
  type: string
- name: storageAccountName
  type: string
- name: storageAccountAccessKey
  type: string
- name: storageContainerName
  type: string
- name: FullProcess
  type: boolean
- name: FunctionApp

jobs:
- job: GetFunctionAppInfo
  condition: ${{ or(eq(parameters.FullProcess, true), eq(parameters.FunctionApp, true)) }}
  steps:
    
    - template: Modules/azurepowershell.yaml

    - task: AzurePowerShell@5
      displayName: 'Get Function App Info'
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptPath: '$(Build.SourcesDirectory)/Templates/Scripts/function_app_info.ps1'
        ScriptArguments: '-resourceGroup "${{parameters.resourcegroup}}" -outputFilePath "${{parameters.resourcegroup}}_${{parameters.outputFileName}}"'
        azurePowerShellVersion: LatestVersion
        
    - task: AzurePowerShell@5
      displayName: 'Upload File to Azure Blob Storage'
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline: |
          $filePath = "$(Agent.BuildDirectory)/${{parameters.resourcegroup}}_${{parameters.outputFileName}}"
          $blobName = '${{parameters.ContainerFolder}}/${{parameters.resourcegroup}}_${{parameters.outputFileName}}'

          $storageContext = New-AzStorageContext -StorageAccountName $(storageAccountName) -StorageAccountKey $(storageAccountAccessKey)
          Set-AzStorageBlobContent -Context $storageContext -Container $(storageContainerName) -File $filePath -Blob $blobName -Force

        azurePowerShellVersion: 'LatestVersion'