parameters:
- name: outputFileName
  default: "KeyVault.txt"
- name: ContainerFolder
  default: "keyvaultinfo"
- name: azureSubscription
  type: string
- name: resourcegroup
  type: string
- name: storageAccountName
  type: string
- name: storageAccountAccessKey
  type: string
- name: storageContainerName
  type: string
- name: FullProcess
  type: boolean
- name: KeyVault

jobs:
- job: GetKeyVaultInfo
  condition: ${{ or(eq(parameters.FullProcess, true), eq(parameters.KeyVault, true)) }}
  steps:

  - template: Modules/azurepowershell.yaml

  - task: AzurePowerShell@5
    displayName: 'Get Key Vault Info'
    inputs:
      azureSubscription: $(azureSubscription)
      ScriptPath: '$(Build.SourcesDirectory)/Templates/Scripts/key_vault_info.ps1'
      ScriptArguments: '-resourceGroup "${{parameters.resourcegroup}}"-outputFilePath "${{parameters.resourcegroup}}_${{parameters.outputFileName}}"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Upload File to Azure Blob Storage'
    inputs:
      azureSubscription: $(azureSubscription)
      ScriptPath: '$(Build.SourcesDirectory)/Templates/Scripts/upload_to_blob.ps1'
      ScriptArguments: '-resourceGroup "${{parameters.resourcegroup}}" -storageContainerName "$(storageContainerName)" -blobName "${{parameters.ContainerFolder}}/${{parameters.resourcegroup}}_${{parameters.outputFileName}}" -outputFileName ${{parameters.outputFileName}} -storageAccountName "$(storageAccountName)" -storageAccountAccessKey "$(storageAccountAccessKey)"'
      azurePowerShellVersion: LatestVersion

  # - task: AzurePowerShell@5
  #   displayName: 'Upload File to Azure Blob Storage'
  #   inputs:
  #     azureSubscription: $(azureSubscription)
  #     ScriptType: 'InlineScript'
  #     Inline: |
  #       $filePath = "${{parameters.resourcegroup}}_${{parameters.outputFileName}}"
  #       $blobName = '${{parameters.ContainerFolder}}/${{parameters.resourcegroup}}_${{parameters.outputFileName}}'

  #       $storageContext = New-AzStorageContext -StorageAccountName $(storageAccountName) -StorageAccountKey $(storageAccountAccessKey)
  #       Set-AzStorageBlobContent -Context $storageContext -Container $(storageContainerName) -File $filePath -Blob $blobName -Force

  #     azurePowerShellVersion: 'LatestVersion'

