parameters:
- name: outputFileName
  default: "StorageAccount.txt"
- name: ContainerFolder
  default: "storageaccountinfo"
- name: azureSubscription
  type: string
- name: resourcegroup
  type: string
- name: storageAccountName
  type: string
- name: storageAccountAccessKey
  type: string
- name: storageContainerName
  type: string
- name: FullProcess
  type: boolean
- name: StorageAccount

jobs:
- job: GetStorageAccountInfo
  condition: ${{ or(eq(parameters.FullProcess, true), eq(parameters.StorageAccount, true)) }}
  steps:

  - template: Modules/azurepowershell.yaml

  - task: AzurePowerShell@5
    displayName: 'Get Storage Account Info'
    inputs:
      azureSubscription: $(azureSubscription)
      ScriptPath: '$(Build.SourcesDirectory)/Templates/Scripts/storage_account_info.ps1'
      ScriptArguments: '-resourceGroup "${{parameters.resourcegroup}}" -outputFilePath "${{parameters.resourcegroup}}_${{parameters.outputFileName}}"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Upload File to Azure Blob Storage'
    inputs:
      azureSubscription: $(azureSubscription)
      ScriptPath: '$(Build.SourcesDirectory)/Templates/Scripts/upload_to_blob.ps1'
      ScriptArguments: '-resourceGroup "${{parameters.resourcegroup}}" -storageContainerName "$(storageContainerName)" -outputFilePath "${{parameters.resourcegroup}}_${{parameters.outputFileName}}" -blobName "${{parameters.ContainerFolder}}/${{parameters.resourcegroup}}_${{parameters.outputFileName}}" -outputFileName ${{parameters.outputFileName}} -storageAccountName "$(storageAccountName)" -storageAccountAccessKey "$(storageAccountAccessKey)"'
      azurePowerShellVersion: LatestVersion